---
- hosts: minecraftmaster
  vars_files:
    - vars/pluginlist.yml
    - vars/whitelist_players.yml
  vars:
    certbot_auto_renew_user: nginx
    certbot_auto_renew_minute: 20
    certbot_auto_renew_hour: 5
  tasks:

    - include_role:
        name: ansiblebit.oracle-java

    - include_role:
        name: install_rcon

    - name: configure the mc server
      include_role:
        name: nolte.minecraft
      vars:
        minecraft_version: 1.13.1
        minecraft_server: spigot
        minecraft_eula_accept: "true"
        minecraft_plugins_set_version: "server"
        minecraft_plugin_sets: "{{ pluginset }}"
        minecraft_ops:
          - nolte07
          - _BlueBeaver_
          - m4yl0n
        minecraft_whitelist: "{{ whitelist_users }}"
        minecraft_server_properties:
          server-port: 25565
          rcon.port: 25564
          enable-rcon: true
          rcon.password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation') }}"
          white-list: true
          enable-command-block: true
          motd: "Amazing Minecraft Server"
          online-mode: true
          resource-pack: http://backup.just-mfg.de/Gerudoku_Faithful_3D_Models_Add-on.zip

    - name: open the gameport for external usage
      firewalld:
        port: 25565/tcp
        permanent: true
        state: enabled
      notify: restart firewalld


    - name: close the rcon for external usage
      firewalld:
        port: 25564/tcp
        permanent: true
        state: disabled
      notify: restart firewalld

    - firewalld:
        port: 8123/tcp
        permanent: true
        state: enabled
      notify: restart firewalld

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
