#cloud-config

package_upgrade: true

packages:
  - git
  - firewalld

users:
  - name: ansible
    gecos: Ansible Controll User
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id: ansiblemanagement
