---
- hosts: minecraftgameserver
  vars_files:
    - ./../vars/facts_mc_node.yml
  become: true
  tasks:

     - name: execute backup
       block:
        - name: deactivate save for backup time
          shell: "/usr/local/bin/rcon-cli --port 25564 --password '{{ mc_rcon_password }}' save-off"

        - name: Change the working directory to somedir/ before executing the command.
          shell: tar --exclude='./server/shared/logs' --exclude='./plugins/shared/dynmap' -czvf /tmp/backup-{{ansible_date_time.iso8601_basic_short}}.tar.gz .
          args:
            chdir: /opt/minecraft/
          async: 1000
          poll: 0
          register: backup_sleeper

        - name: 'YUM - check on async task'
          async_status:
            jid: "{{ backup_sleeper.ansible_job_id }}"
          register: job_result
          until: job_result.finished
          retries: 60
          delay: 30

       always:
         - name: activate autosave
           shell: "/usr/local/bin/rcon-cli --port 25564 --password '{{ mc_rcon_password }}' save-on"
         - name: activate autosave
           shell: "/usr/local/bin/rcon-cli --port 25564 --password '{{ mc_rcon_password }}' say backup finished"
