---

- set_fact:
    serverName: localhost.localdomain
    certbot_admin_email: https@servercheck.in
    certbot_create_if_missing: true
#    certbot_create_standalone_stop_services:
#      - nginx
    certbot_create_method: standalone
 #   certbot_certs:
#      - domains:
#          - "dynmap.just-mfg.de"



#    certbot_create_standalone_stop_services:
#      - nginx

- include_role:
    name: geerlingguy.nginx
  vars:
    nginx_use_ppa: true
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "{{ serverName }}"
#        server_name_redirect: "dynmap.just-mfg.de"
        root: "/var/www/dynmap.just-mfg.de"
        index: "index.php index.html index.htm"
#        extra_parameters: |
#          ssl_certificate     /etc/letsencrypt/csr/0000_csr-certbot.pem;
#          ssl_certificate_key /etc/letsencrypt/keys/0000_key-certbot.pem;
#          ssl_protocols       TLSv1.1 TLSv1.2;
#          ssl_ciphers         HIGH:!aNULL:!MD5;

- include_role:
    name: geerlingguy.certbot

- firewalld:
    port: 433/tcp
    permanent: true
    state: enabled
  notify: restart firewalld
